import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MobileTabBar from "../components/MobileTabBar";
import Navbar from "../components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <div
          className={`mx-auto min-h-screen max-w-xl bg-white pb-20 md:pb-0 ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="hidden md:block">
            <Navbar />
          </div>
          {children}
          <MobileTabBar />
        </div>
      </body>
    </html>
  );
}
